// AUTO-GENERATED by scripts/parse-deworming-csv.ts
// Source: src/lib/data/deworming-vaccination.csv
// Do not edit by hand — re-run the parser instead.
//
// 2026-08-24: blank slate — all deworming/vaccination data wiped pending
// re-import from the new spreadsheets. Re-run the parser after dropping the
// new CSV into src/lib/data/ to repopulate.

import type { MedicalEntry } from "./medical-data";

export const importedDewormingEntries: MedicalEntry[] = [];

export const importedVaccinationEntries: MedicalEntry[] = [];

export interface YardWideDeworming {
  id: string;
  date: string; // ISO YYYY-MM-DD
  drug: string;
  dose: string; // e.g. "Single Dose (0.2 mg/kg)" or "5-day Power Pack (5 mg/kg/day)"
}

export const yardWideDewormings: YardWideDeworming[] = [];

export const nextVaccinationByAnimal: Map<string, string> = new Map();

export function getNextVaccinationDue(animalName: string): string | null {
  return nextVaccinationByAnimal.get(animalName) ?? null;
}

export const scheduledVaccinationEntries: MedicalEntry[] = [];

export const importedMedicalEntries: MedicalEntry[] = [];
