// AUTO-GENERATED by scripts/parse-adoption-csv.ts
// Source: src/lib/data/donkey-adoption.csv
// Do not edit by hand — re-run the parser instead.
//
// 2026-08-24: blank slate — all profile data wiped pending re-import from the
// new spreadsheets. Re-run the parser after dropping the new CSVs into
// src/lib/data/ to repopulate.

import type { MedicalEntry } from "./medical-data";

export interface DonkeyProfile {
  name: string;
  herd: string;
  sex: string;
  size: string;
  color: string;
  birthDate: string | null;
  age: string;
  origin: string;
  adoptedFrom: string;
  intakeDate: string | null;
  microchip: string | null;
  needsChip: boolean;
  notes: string;
  specialNeedsDetail: string;
  momBabyCount: number;
  isBondedPair: boolean;
  isSpecialNeeds: boolean;
  isOver20: boolean;
  lastAnnualExam: string | null;
  parents: string[];
  children: string[];
  bondedWith: string[];
}

export const donkeyProfiles: Map<string, DonkeyProfile> = new Map();

export function getDonkeyProfile(animalName: string): DonkeyProfile | null {
  return donkeyProfiles.get(animalName) ?? null;
}

export const annualExamEntries: MedicalEntry[] = [];

export const revisedMedicalEntries: MedicalEntry[] = [];

export interface SanctuaryStats {
  totalDonkeys: number;
  momBaby: number;
  bondedPairs: number; // halves / 2
  specialNeeds: number;
  seniors: number;
  needsChip: number;
}

export const sanctuaryStats: SanctuaryStats = {
  totalDonkeys: 0,
  momBaby: 0,
  bondedPairs: 0,
  specialNeeds: 0,
  seniors: 0,
  needsChip: 0,
};
