// AUTO-GENERATED by scripts/parse-power-pack-csv.ts
// Source: src/lib/data/power-pack-doses.csv
// Do not edit by hand — re-run the parser instead.
//
// 2026-08-24: blank slate — all dosing data wiped pending re-import from the
// new spreadsheets. Re-run the parser after dropping the new CSV into
// src/lib/data/ to repopulate.

import type { MedicalEntry } from "./medical-data";

export interface DewormingDosage {
  category: string;
  doses: number;
  doseGrams: number;
}

export const powerPackEntries: (MedicalEntry & { drug: string })[] = [];

export const dewormingDosages: Map<string, DewormingDosage> = new Map();

export function getDewormingDosage(animalName: string): DewormingDosage | null {
  return dewormingDosages.get(animalName) ?? null;
}
