// AUTO-GENERATED by scripts/parse-schedules-and-events.ts
// Sources: src/lib/data/angels-schedule.csv, pegasus-schedule.csv, brave-events.csv
// Do not edit by hand — re-run the parser instead.
//
// 2026-08-24: blank slate — all schedule/event data wiped pending re-import
// from the new spreadsheets. Re-run the parser after dropping the new CSVs
// into src/lib/data/ to repopulate.

import type { MedicalEntry } from "./medical-data";

export const scheduledDewormingEntries: MedicalEntry[] = [];

export const braveActualEntries: MedicalEntry[] = [];

export interface DonkeyWeight {
  lbs: number;
  kg: number;
}

// Per-donkey weight from CSVs (most recent value seen).
export const donkeyWeights: Map<string, DonkeyWeight> = new Map();

export function getDonkeyWeight(animalName: string): DonkeyWeight | null {
  return donkeyWeights.get(animalName) ?? null;
}
