// AUTO-GENERATED by scripts/parse-trimming-csv.ts
// Source: src/lib/data/donkey-trimming-notes.csv
// Do not edit by hand — re-run the parser instead.
//
// 2026-08-24: blank slate — all trim data wiped pending re-import from the
// new spreadsheets. Re-run the parser after dropping the new CSV into
// src/lib/data/ to repopulate.

import type { CareVisit } from "./hoof-dental-data";

export interface TrimProfile {
  /** ISO date of the most recent trim, per the CSV's "Last Trim" column. */
  lastTrim: string | null;
  /** Sedation / pre-meds / valerian root protocols. */
  preTrimTreatment: string;
  /** Per-donkey trimming approach (sling, halter, who's nearby, etc.). */
  protocols: string;
  /** Squish pad usage notes. */
  squishPads: string;
  /** Most recent free-text notes from the trim session. */
  recentNotes: string;
  /** ISO date of the last training/desensitization session. */
  trainingDate: string | null;
  /** Free-text notes on training progress (lifting feet, building trust, etc.). */
  trainingNotes: string;
}

export const importedHoofVisits: CareVisit[] = [];

export const trimProfiles: Map<string, TrimProfile> = new Map();

export function getTrimProfile(animalName: string): TrimProfile | null {
  return trimProfiles.get(animalName) ?? null;
}
